/**
 * 
 */
package com.banking.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents the Account entity for storing customer banking details.
 * 
 * <p>This entity maps to the database table <b>Bank_Details</b> and 
 * contains information related to the customer's account such as 
 * account type, balance, and current status.</p>
 * 
 * <p>Used by the Banking/Wallet REST API for account-related operations 
 * like create, update, deposit, withdraw, and transfer.</p>
 * 
 * @author Madhusudan Dande
 */
@Entity
@Table(name = "Bank_Details")
public class Account {

    /**
     * Unique account identifier (Primary Key).
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long accountId;

    /**
     * Customer ID to whom this account belongs.
     */
    private long customerId;

    /**
     * Type of the account (e.g., "Savings", "Current", "Wallet").
     */
    private String accountType;

    /**
     * Current available balance in the account.
     */
    private double balance;

    /**
     * Current status of the account (e.g., "Active", "Inactive", "Closed").
     */
    private String status;

    // ---------------------------------------------------------
    // Getters and Setters
    // ---------------------------------------------------------

    /**
     * Returns the account ID.
     * @return accountId
     */
    public long getAccountId() {
        return accountId;
    }

    /**
     * Sets the account ID.
     * @param accountId the unique ID of the account
     */
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }

    /**
     * Returns the customer ID.
     * @return customerId
     */
    public long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the customer ID linked with the account.
     * @param customerId the ID of the customer
     */
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    /**
     * Returns the type of the account.
     * @return accountType
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the type of the account (e.g., Savings or Current).
     * @param accountType the type of the account
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Returns the current balance of the account.
     * @return balance
     */
    public double getBalance() {
        return balance;
    }

    /**
     * Updates the account balance.
     * @param balance the new balance value
     */
    public void setBalance(double balance) {
        this.balance = balance;
    }

    /**
     * Returns the account status.
     * @return status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the current account status (Active/Inactive/Closed).
     * @param status the status of the account
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
