/**
 * 
 */
package com.banking.model;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a transaction record between two accounts in the banking system.
 * 
 * <p>This entity stores information related to each transaction such as 
 * source account, destination account, amount transferred, timestamp, and status.</p>
 * 
 * <p>It is used for maintaining a complete transaction history and 
 * tracking the flow of funds in the system.</p>
 * 
 * @author Madhusudan Dande
 */
@Entity
@Table(name = "Transaction")
public class Transaction {

    /**
     * Unique transaction identifier (Primary Key).
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long transactionId;

    /**
     * Account ID from which the amount is debited.
     */
    private Long fromAccountId;

    /**
     * Account ID to which the amount is credited.
     */
    private Long toAccountId;

    /**
     * Amount transferred during the transaction.
     */
    private double amount;

    /**
     * Date and time when the transaction occurred.
     */
    private LocalDateTime timestamp;

    /**
     * Current status of the transaction (e.g., "SUCCESS", "FAILED", "PENDING").
     */
    private String status;

    // ---------------------------------------------------------
    // Getters and Setters
    // ---------------------------------------------------------

    /**
     * Returns the transaction ID.
     * @return transactionId
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the transaction ID.
     * @param transactionId unique identifier for the transaction
     */
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Returns the source account ID.
     * @return fromAccountId
     */
    public Long getFromAccountId() {
        return fromAccountId;
    }

    /**
     * Sets the source account ID.
     * @param fromAccountId account ID from which the amount is debited
     */
    public void setFromAccountId(Long fromAccountId) {
        this.fromAccountId = fromAccountId;
    }

    /**
     * Returns the destination account ID.
     * @return toAccountId
     */
    public Long getToAccountId() {
        return toAccountId;
    }

    /**
     * Sets the destination account ID.
     * @param toAccountId account ID to which the amount is credited
     */
    public void setToAccountId(Long toAccountId) {
        this.toAccountId = toAccountId;
    }

    /**
     * Returns the transaction amount.
     * @return amount
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the transaction amount.
     * @param amount value of money transferred
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * Returns the timestamp of the transaction.
     * @return timestamp
     */
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp of the transaction.
     * @param timestamp date and time of transaction occurrence
     */
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the transaction status.
     * @return status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the current transaction status.
     * @param status status of the transaction (e.g., SUCCESS, FAILED)
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
